# Generated by Django 3.1.1 on 2020-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('main_image', models.CharField(max_length=255)),
                ('gallery', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=6)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available_qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('specifications', models.CharField(max_length=255)),
                ('new_product', models.BooleanField()),
                ('video', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meta_description', models.CharField(max_length=255)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.category')),
            ],
        ),
    ]
