# Generated by Django 3.1.1 on 2020-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attach_file',
            field=models.FileField(default='non', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
