# Generated by Django 3.1.1 on 2020-10-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20201027_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
