# Generated by Django 3.1.1 on 2020-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20201027_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metric_num',
            field=models.CharField(default='кг.', max_length=6),
        ),
    ]
