# Generated by Django 3.1.1 on 2020-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_product_metric_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
        migrations.AddField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='attached_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
