# Generated by Django 3.1.1 on 2020-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20201028_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(default='None', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(default='None', upload_to='images'),
        ),
    ]
