# Generated by Django 3.1.1 on 2020-10-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20201028_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery2',
        ),
    ]
