# Generated by Django 3.1.1 on 2020-10-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20201028_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery1',
            field=models.ImageField(default='image', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gallery2',
            field=models.ImageField(default='image', upload_to='images'),
            preserve_default=False,
        ),
    ]
